# Generated by Django 4.2.30 on 2026-08-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('bd', '0018_perfilpatrocinador_aprobado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('BLOQUEADO', 'Bloqueado'), ('LIBERADO', 'Liberado')], default='BLOQUEADO', max_length=15)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='bd.incidencia')),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='bd.perfilpatrocinador')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['estado', 'incidencia'], name='recursos_re_estado_58174a_idx'),
                    models.Index(fields=['patrocinador'], name='recursos_re_patroci_a31387_idx'),
                ],
            },
        ),
    ]
