# Generated by Django 4.2.30 on 2026-08-22 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd', '0022_incidencia_oculto_por_fraude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFraude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_fraude', to='bd.incidencia')),
                ('usuario_reporta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraude_reportado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='reportefraude',
            constraint=models.UniqueConstraint(fields=('incidencia', 'usuario_reporta'), name='un_reporte_fraude_por_usuario_por_incidencia'),
        ),
    ]
