/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "primary": "#0058be",
        "surface-container-highest": "#d3e4fe",
        "inverse-primary": "#adc6ff",
        "background": "#f8f9ff",
        "on-background": "#0b1c30",
        "surface-container": "#e5eeff",
        "on-primary": "#ffffff",
        "secondary-container": "#6cf8bb",
        "on-error-container": "#93000a",
        "surface-container-low": "#eff4ff",
        "outline-variant": "#c2c6d6",
        "on-secondary-container": "#00714d",
        "inverse-surface": "#213145",
        "on-surface-variant": "#424754",
        "inverse-on-surface": "#eaf1ff",
        "error": "#ba1a1a",
        "on-surface": "#0b1c30",
        "surface-variant": "#d3e4fe",
        "surface-container-high": "#dce9ff",
      },
      fontFamily: {
        "label-md": ["Montserrat"],
        "body-sm": ["Montserrat"],
        "headline-md": ["Montserrat"],
        "headline-lg-mobile": ["Montserrat"],
        "button-text": ["Montserrat"],
        "title-lg": ["Montserrat"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "button-text": ["16px", { lineHeight: "20px", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "sm": "8px",
        "gutter": "16px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}