# Generated by Django 4.2.30 on 2026-06-20 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd', '0007_animal_edad_estimada_peso_estimado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rescate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_CAMINO', 'En Camino'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='EN_CAMINO', max_length=20)),
                ('fecha_aceptacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('incidencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rescate_activo', to='bd.incidencia')),
                ('rescatista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescates_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
