# Generated by Django 4.2.30 on 2026-07-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescate',
            name='historial',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='rescate',
            name='estado',
            field=models.CharField(choices=[('EN_CAMINO', 'En Camino'), ('EN_SITIO', 'En Sitio'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='EN_CAMINO', max_length=20),
        ),
    ]
