# Generated by Django 4.2.30 on 2026-08-13 01:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescates', '0002_rescate_historial_alter_rescate_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescate',
            name='closure_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Ubicación GPS del voluntario al momento del cierre.', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='rescate',
            name='closure_photo',
            field=models.ImageField(blank=True, help_text='Foto de evidencia tomada al cerrar el rescate.', null=True, upload_to='cierres/%Y/%m/'),
        ),
        migrations.AddIndex(
            model_name='rescate',
            index=models.Index(fields=['rescatista', 'estado'], name='rescates_re_rescati_5cb396_idx'),
        ),
        migrations.AddIndex(
            model_name='rescate',
            index=models.Index(fields=['estado', '-fecha_aceptacion'], name='rescates_re_estado_656ff5_idx'),
        ),
    ]
