# Generated by Django 4.2.30 on 2026-08-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescates', '0003_rescate_closure_location_rescate_closure_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescate',
            name='estado',
            field=models.CharField(choices=[('EN_CAMINO', 'En Camino'), ('EN_SITIO', 'En Sitio'), ('EN_PROCESO', 'En Proceso'), ('EN_TRASLADO', 'En Traslado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='EN_CAMINO', max_length=20),
        ),
    ]
