# Generated by Django 4.2.30 on 2026-06-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidencia',
            old_name='usuario',
            new_name='usuario_reporta',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/perfiles/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol_principal',
            field=models.CharField(choices=[('REPORTERO', 'Reportero'), ('RESCATISTA', 'Rescatista'), ('PATROCINADOR', 'Patrocinador')], default='REPORTERO', max_length=20),
        ),
        migrations.CreateModel(
            name='PerfilRescatista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misiones_completadas', models.IntegerField(default=0)),
                ('horas_campo', models.IntegerField(default=0)),
                ('habilidades', models.JSONField(blank=True, default=list)),
                ('esta_certificado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_rescatista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilPatrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=255)),
                ('capacidad', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('redes', models.CharField(blank=True, max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('nivel', models.CharField(default='SILVER', max_length=50)),
                ('total_donado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('casos_soportados', models.IntegerField(default=0)),
                ('fecha_inicio_coordinacion', models.DateField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_patrocinador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='incidencia',
            name='rescatista_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misiones_activas', to='bd.perfilrescatista'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='patrocinador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_apoyados', to='bd.perfilpatrocinador'),
        ),
        migrations.DeleteModel(
            name='Patrocinador',
        ),
    ]
