# Generated by Django 4.2.30 on 2026-06-09 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_rename_usuario_incidencia_usuario_reporta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='usuario_reporta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
