# Generated by Django 4.2.30 on 2026-06-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0004_roles_acumulables_incidencia_campos_calculados'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
