# Generated by Django 4.2.30 on 2026-06-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0005_folio_incidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
