# Generated by Django 4.2.30 on 2026-06-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0007_animal_edad_estimada_peso_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpatrocinador',
            name='nombre_entidad',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='perfilpatrocinador',
            name='rfc_o_registro',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='perfilpatrocinador',
            name='tipo_entidad',
            field=models.CharField(choices=[('EMPRESA', 'Empresa'), ('REFUGIO', 'Refugio'), ('ASOCIACION', 'Asociación'), ('OTRO', 'Otro')], default='OTRO', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fraud_flags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reputation_score',
            field=models.FloatField(default=100),
        ),
    ]
