# Generated by Django 4.2.30 on 2026-06-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0008_perfilpatrocinador_nombre_entidad_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
