# Generated by Django 4.2.30 on 2026-06-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0009_alter_usuario_managers_remove_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpatrocinador',
            name='telefono_contacto',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='tipo_incidencia',
            field=models.CharField(choices=[('EMERGENCIA', 'Emergencia'), ('EXTRAVIADO', 'Extraviado'), ('CALLEJERO', 'Callejero')], default='EMERGENCIA', max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilpatrocinador',
            name='capacidad',
            field=models.CharField(help_text='Descripción de recursos disponibles (alimento, transporte, veterinaria, etc.)', max_length=255),
        ),
        migrations.AlterField(
            model_name='perfilpatrocinador',
            name='correo',
            field=models.EmailField(help_text='Correo oficial de la entidad', max_length=254),
        ),
        migrations.AlterField(
            model_name='perfilpatrocinador',
            name='nivel',
            field=models.CharField(choices=[('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='SILVER', max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilpatrocinador',
            name='nombre_entidad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='perfilpatrocinador',
            name='rfc_o_registro',
            field=models.CharField(blank=True, help_text='RFC o número de registro legal de la entidad', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilpatrocinador',
            name='tipo_entidad',
            field=models.CharField(choices=[('EMPRESA', 'Empresa'), ('REFUGIO', 'Refugio Animal'), ('ASOCIACION', 'Asociación Protectora'), ('OTRO', 'Otro')], default='OTRO', max_length=50),
        ),
    ]
