# Generated by Django 4.2.30 on 2026-06-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0010_perfilpatrocinador_telefono_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='nombre_caso',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
