# Generated by Django 4.2.30 on 2026-06-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0011_incidencia_nombre_caso'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='nombre_contacto',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='telefono_contacto',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
