# Generated by Django 4.2.30 on 2026-07-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0012_incidencia_contacto_anonimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
