# Generated by Django 4.2.30 on 2026-07-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0013_incidencia_direccion_incidencia_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='ficha_voluntario',
            field=models.TextField(blank=True, default=''),
        ),
    ]
