# Generated by Django 4.2.30 on 2026-07-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0014_incidencia_ficha_voluntario'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='coincidencias_visuales_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
