# Generated by Django 4.2.30 on 2026-07-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0015_incidencia_coincidencias_visuales_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='coincidencias_visuales_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
