# Generated by Django 4.2.30 on 2026-07-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0015_usuario_ubicacion'),
        ('bd', '0016_alter_incidencia_coincidencias_visuales_ids'),
    ]

    operations = [
    ]
