# Generated by Django 4.2.30 on 2026-07-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0017_merge_20260711_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpatrocinador',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='perfilpatrocinador',
            constraint=models.CheckConstraint(check=models.Q(('nombre_entidad__isnull', False), models.Q(('nombre_entidad', ''), _negated=True)), name='datos_entidad_requeridos'),
        ),
    ]
