# Generated by Django 4.2.30 on 2026-08-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0019_perfilpatrocinador_centro_apoyo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de validar'), ('VALIDADO', 'Validado'), ('ATENDIENDOSE', 'En atención'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado'), ('DESESTIMADO', 'Desestimado')], default='PENDIENTE', max_length=50),
        ),
    ]
