# Generated by Django 4.2.30 on 2026-08-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0020_alter_incidencia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='trafico_score',
            field=models.FloatField(default=0),
        ),
    ]
