# Generated by Django 4.2.30 on 2026-08-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0021_incidencia_trafico_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='oculto_por_fraude',
            field=models.BooleanField(default=False, help_text='Se oculta de mapa/disponibles al llegar a 3 denuncias, hasta que un admin lo resuelva.'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='reportes_fraude_count',
            field=models.IntegerField(default=0),
        ),
    ]
