# Generated by Django 4.2.30 on 2026-08-15 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reporte_aceptado', 'Tu reporte fue aceptado'), ('reporte_cerrado', 'Tu reporte fue cerrado'), ('reporte_cancelado', 'El rescate de tu reporte fue cancelado'), ('centro_publicacion', 'Publicación de un centro que sigues'), ('centro_aprobado', 'Tu centro fue aprobado'), ('centro_rechazado', 'Tu centro fue rechazado')], max_length=40)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.CharField(blank=True, default='', max_length=300)),
                ('enlace', models.CharField(blank=True, default='', max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'leida', '-created_at'], name='notificacio_usuario_f689f1_idx')],
            },
        ),
    ]
