# Generated by Django 4.2.30 on 2026-08-11 01:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd', '0019_perfilpatrocinador_centro_apoyo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguidorCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='bd.perfilpatrocinador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_seguidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResenaCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, default='')),
                ('respuesta', models.TextField(blank=True, default='')),
                ('respuesta_fecha', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='bd.perfilpatrocinador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_centros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicacionCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='centros/publicaciones/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='bd.perfilpatrocinador')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='seguidorcentro',
            constraint=models.UniqueConstraint(fields=('centro', 'usuario'), name='seguidor_unico_por_centro'),
        ),
        migrations.AddConstraint(
            model_name='resenacentro',
            constraint=models.UniqueConstraint(fields=('centro', 'usuario'), name='resena_unica_por_usuario_y_centro'),
        ),
    ]