# Generated by Django 4.2.30 on 2026-07-14 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bd', '0015_usuario_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaDuplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de confirmación'), ('CONFIRMADA', 'Confirmada — mismo caso'), ('RECHAZADA', 'Rechazada — casos distintos')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resuelto_at', models.DateTimeField(blank=True, null=True)),
                ('incidencia_candidata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerido_como_candidata', to='bd.incidencia')),
                ('incidencia_nueva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencia_duplicado', to='bd.incidencia')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
